### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by onsae09** [jwdeveloper/JW_Piano#14]
After downloading and launching the JWpiano app, I pasted this token into the window and pressed connect, but it only shows can't connect to server. I tried reloading the plugin or reloading the server, same thing.

**Comment by onsae09** [comment]
Incidentally, I found this bug when I reloaded the server.

[12:47:56] [Server thread/INFO]: [JW_Piano] Enabling JW_Piano v1.2.3
[12:47:57] [Server thread/INFO]: [JW_Piano] [Info] Websocket runs on: [serverip]:443
[12:47:57] [Server thread/INFO]: [JW_Piano] minecraft
[12:47:57] [WebSocketSelector-13690/ERROR]: [org.java_websocket.server.WebSocketServer] Shutdown due to fatal error
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:562) ~[JW_Piano.jar:?]
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:362) ~[JW_Piano.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[12:47:57] [WebSocketSelector-13690/INFO]: 
[Critical Error] Web socket error 
[Reason] Address already in use
[Exception type] BindException
----------------------------------------------------------------------------------------------------

at line  -2    in sun.nio.ch.Net.bind0() 
at line  555   in sun.nio.ch.Net.bind() 
at line  337   in sun.nio.ch.ServerSocketChannelImpl.netBind() 
at line  294   in sun.nio.ch.ServerSocketChannelImpl.bind() 
at line  89    in sun.nio.ch.ServerSocketAdaptor.bind() 
at line  562   in org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread() 
at line  362   in org.java_websocket.server.WebSocketServer.run() 
at line  840   in java.lang.Thread.run() 
----------------------------------------------------------------------------------------------------

**Comment by jack1888x** [comment]
Have you ever fixed it
